artifact_uri: file:///home/bdudas/obesity_challange/mlruns/410825968021990540/b63c6d7898c64bfca0df037a416fb99d/artifacts
end_time: 1766597530800
entry_point_name: ''
experiment_id: '410825968021990540'
lifecycle_stage: active
run_id: b63c6d7898c64bfca0df037a416fb99d
run_name: transformerVAE_equalfactors25
source_name: ''
source_type: 4
source_version: ''
start_time: 1766596106859
status: 3
tags: []
user_id: bdudas
