free_bits: 0.3
kl_warmup_steps: 10000
noise_warmup: 10000
kldFactor: 0.001
reconFactor: 1.
classFactor: .1
multiple_optimizers: True
beta_start: 0.80
kld_mode: "linear"
class_warmup_steps: 20000 
categoryWeights: [1.,1.,1.,1.]
